# Load the required gems/libraries.
require 'rubygems'
require 'bundler/setup'
require 'active_record'
require 'sqlite3'
require 'logger'

# Load all of our ActiveRecord::Base objects.
load 'models/category.rb' # categories table
load 'models/customer.rb' # customers table
load 'models/product.rb'  # products table
load 'models/province.rb' # provinces table
load 'models/ghost.rb'    # ghosts table

# Establish our connection to our serverless sqlite3 database.
ActiveRecord::Base.establish_connection :adapter => 'sqlite3', :database => 'db/development.sqlite3'

# For debugging purposes, uncomment this line to see the SQL generated by ActiveRecord:
# ActiveRecord::Base.logger = Logger.new(STDOUT)

# Uncomment this line to make the logger output look nicer in Windows.
# ActiveSupport::LogSubscriber.colorize_logging = false